### ISSUE TITLE
'opencv2/highgui/cap_ios.h' file not found

### ISSUE THREAD

**Issue by zziazm** [June0611/EyeBlickCheck#1]
您好，我已经下载了opencv2.framework和这两个xml文件并且拖入到了从github下载的工程里，但是运行的时候还是报错'opencv2/highgui/cap_ios.h' file not found，请问怎么处理

**Comment by June0611** [comment]
报这个错误应该是sdk的版本不对,我发给您一个百度云地址,里面包含了所需要的三个文件,您那儿导入下试试
链接: https://pan.baidu.com/s/1slQ8MQT 密码: ju5f

**Comment by zziazm** [comment]
多谢，我去试试

**Comment by zziazm** [comment]
您好，我去网盘上下载导入工程后现在运行还是报错：'iflyMSC/IFLYFaceSDK.h' file not found,这个sdk也需要下载吗

**Comment by June0611** [comment]
这个是讯飞的识别SDK ,是不需要的,把引用该头文件的地方去除掉就可以

**Comment by zziazm** [comment]
<img width="885" alt="2017-07-18 10 19 29" src="https://user-images.githubusercontent.com/9669530/28297913-fe1a4550-6ba2-11e7-907f-cd8b0e696a85.png">
这个讯飞的sdkdemo里好像没有，跟讯飞相关的代码都报错了

**Comment by June0611** [comment]
我这儿显示你没有收到附件.附上百度地址,备用,链接: https://pan.baidu.com/s/1geJRu3D 密码: v7a9

**Comment by zziazm** [comment]
多谢，可以了

**Comment by June0611** [comment]
不客气

**Comment by dongcidongci** [comment]
'opencv2/highgui/cap_ios.h' file not found,我是在你的网盘里面下载的opencv库和分类器,导进去还是报错,求大神指导

**Comment by dongcidongci** [comment]
build succeed了,多谢大神的共享
