### ISSUE TITLE
找不到这个文件是因为还要导入库吗

### ISSUE THREAD

**Issue by wsx1994** [June0611/EyeBlickCheck#2]
<img width="1012" alt="pasted graphic 1" src="https://user-images.githubusercontent.com/33861158/53559735-bed79780-3b85-11e9-88e9-155187418f96.png">
我编译之后就报错了，是因为我没有导入iflyMSC.framework吗

**Comment by June0611** [comment]
这个库在这个项目中没有作用，直接删掉就行

**Comment by June0611** [comment]
这个库在这个项目中没有作用，直接删掉就行

**Comment by June0611** [comment]
这个库在这个项目中没有作用，直接删掉就行
